name: Copy Log to GitHub Pages Repo

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Log repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git clone https://x-access-token:${{ secrets.GH_PAGES_TOKEN }}@github.com/YChiasma/Log.git Log

      - name: Clone GitHub Pages repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git clone https://x-access-token:${{ secrets.GH_PAGES_TOKEN }}@github.com/YChiasma/YChiasma.github.io.git gh-pages
          
      - name: Copy Log
        run: |
          rsync -av --exclude=".*" Log/log gh-pages/log
          rsync -av --exclude=".*" Log/log-dev gh-pages/log-dev
          cd gh-pages
          git add .
          git commit -m "Update Streak from Log repo [skip ci]" || echo "No changes to commit"
          git push
